feat(t9): implementation of authorization
alexey-samokhin/news-site-frontend-samokhin-a pull request #4
Opened 2023-06-24 12:31 UTC by alexey-samokhin

2023-06-27 09:18 UTC, skaptelinin commented on .env
> +REACT_APP_BASE_URL=http://localhost:8000/api
.env не должно быть в репозитории. Проверь .gitignore

2023-06-27 09:21 UTC, skaptelinin commented on src/api/services/posts.service.ts
> +  const response = await api.get(`${POST_URL}`);
Здесь нет смысла в конкатенации

2023-06-27 09:24 UTC, skaptelinin commented on src/api/services/posts.service.ts
> +import { api } from '../axios-instance';
Нейминг файлов должен быть консистентным. У тебя же компоненты в camelCase, axios - kebab-case, эндпоинты - dot.split. Если у тебя нет правил, которые объясняют почему такие различия в нейминге - лучше держи все в camelCase

2023-06-27 09:28 UTC, skaptelinin commented on src/components/Containers/Header/Header.styles.ts
> +    .header__auth a:not(:last-child) {
В БЭМ нельзя использовать имена HTML тэгов в стилях. Если ты придумаешь название для такого элемента, то этот стиль будет гораздо лучше читаться.

2023-06-27 09:30 UTC, skaptelinin commented on src/components/Containers/Footer/Footer.tsx
> +import { ContainerStyled } from '@/styles/container.styles';
ContainerStyled выглядит достаточно общей штукой. Я бы внутри @/styles настроил экспорты таким образом, чтобы можно было делать так
```
import { ContainerStyled } from '@/styles';
```

2023-06-27 09:32 UTC, skaptelinin commented on src/components/Containers/Header/Header.tsx
> +          <img className="header__logo" src={Logo} alt="React Logo" />
В alt нужно писать что-нибудь, похожее на правду) У тебя тут явно не лого реакта)

2023-06-27 09:33 UTC, skaptelinin commented on src/components/Pages/Auth/SignUp.tsx
> +import { ContainerStyled } from '@/styles/container.styles';
Не забывай разделять импорты)

2023-06-27 09:34 UTC, skaptelinin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
>  import type { FC } from 'react';
Импорты из одной библиотеки лучше группировать.
```
import { useEffect } from 'react';
import type { FC } from 'react';
import { useDispatch, useSelector } from 'react-redux';
```

2023-06-27 09:35 UTC, skaptelinin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
> +  const posts: Post[] = useSelector((store: any) => store?.posts.posts);
Избегай использование any. Посмотри как можно типизировать `useSelector`

2023-06-27 09:36 UTC, skaptelinin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
> +  }, [dispatch]);
Тут скорее всего линтер ругается, но функцию dispatch можно не указывать в зависимостях. Она гарантированно не меняется после рендера.

2023-06-27 09:41 UTC, skaptelinin commented on src/redux/actions/actionsCreators.ts
> +export const getPosts = () => ({
У редакса должны быть типы для actions creators. Скорее всего там что-то такое
```
type ActionCreator<Payload = void> = (payload?: Payload) => {
  type: string;
  payload?: Payload;
}
```
и далее ты можешь писать
```
export const setPosts: ActionCreator<Post[]> = (payload) => ({
  type: NEWS_RECEIVED,
  payload,
});
```

2023-06-27 09:42 UTC, skaptelinin commented on src/redux/reducers/postsReducer.ts
> +const initialState = {
Эту штуку тоже надо типизировать.

2023-06-27 09:45 UTC, skaptelinin commented on src/redux/reducers/postsReducer.ts
> +  error: null,
На текущем этапе я бы использовал просто флаг hasError. На практике у тебя будет куча статусов и сообщений, и зачастую логика обработки ошибок сильно сложнее логики успешного действия)

2023-06-27 09:46 UTC, skaptelinin commented on src/redux/reducers/postsReducer.ts
> +const postsReducer = (state = initialState, action: any) => {
Для action у редакса должен быть встроенный тип.

2023-06-27 09:46 UTC, skaptelinin commented on src/redux/sagas/postsSaga.ts
> +  } catch (error: any) {
У error тип unknown, и его не стоит менять.

2023-06-27 09:55 UTC, skaptelinin commented on package.json
> +    "@emotion/styled": "^11.11.0",
на будущее - emotion делает плюс-минус тоже самое, что и styled-components. Потому имеет смысл выбрать для кастомных стилей ту же технологию, что и используют UI-фреймворк (в данном случае material-ui)

2023-06-27 11:04 UTC, alexey-samokhin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
>  import type { FC } from 'react';
@skaptelinin это линтер так настроен, или лучше убрать это правило?

2023-06-27 11:04 UTC, alexey-samokhin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
> +  }, [dispatch]);
@skaptelinin да линтер просит указать dispatch

2023-06-27 11:05 UTC, alexey-samokhin commented on src/components/Containers/Header/Header.styles.ts
> +    .header__auth a:not(:last-child) {
@skaptelinin сложно придумать слово для замены header. даже синонимов нет подходящих.

2023-06-27 11:05 UTC, skaptelinin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
>  import type { FC } from 'react';
Если линтер так настроен, то оставь

2023-06-27 11:08 UTC, skaptelinin commented on src/components/Containers/Header/Header.styles.ts
> +    .header__auth a:not(:last-child) {
Тебе нужно придумать имя для `a:not(:last-child)`. Но еще лучше попытаться сделать разметку таким образом, чтобы этого марджина не было вообще. Например, если это требуется для отступа между разными блоками - в большинстве случаев лучше использовать flex-gap

2023-06-27 14:32 UTC, skaptelinin requested changes

2023-06-27 14:32 UTC, skaptelinin commented on .env
> +REACT_APP_BASE_URL=http://localhost:8000/api
.env все еще в репозитории

2023-06-27 14:32 UTC, skaptelinin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
> +  const { posts } = useSelector((store: AppState) => store?.posts);
Здесь же стоит еще отрисовать ошибку и экран загрузки.

2023-06-27 14:32 UTC, skaptelinin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
> +      {posts.map((post: Post) => (
Можно сделать так)
```
{posts.map(({ id, title, content }) => (
    <PostItem
          key={id}
          title={title}
          description={content}
        />
)}
```

2023-06-27 14:32 UTC, skaptelinin commented on src/redux/actions/actionsCreators.ts
> +type ActionCreator<Payload = void> = (payload?: Payload) => {
У редакса должен быть встроенный тип. Я предложил это в качестве примера)

2023-06-27 14:32 UTC, skaptelinin commented on src/redux/reducers/postsReducer.ts
> +        hasError: false,
hasError: true,

2023-06-27 14:32 UTC, skaptelinin commented on src/api/services/postsService.ts
> +
Здесь лучше указать возвращемый тип
```
const getAllPosts = async (): Promise<Post[]> => {
  const response = await api.get<Post[]>(POST_URL);
  return response.data;
};
```
И дальше тебк гораздо проще будет данные запрашивать, тайпскрипт будет сразу все понимать

2023-06-27 14:32 UTC, skaptelinin commented on src/redux/reducers/postsReducer.ts
> +  payload: Post[];
У тебя может быть совершенно разный payload, плюс он опциональный. Погугли, как нужно типизировать редакс. В крайнем случае, используй generic type, как в actionsCreators

2023-06-27 14:44 UTC, alexey-samokhin commented on src/components/Pages/Main/components/PostsList/PostsList.tsx
> +      {posts.map((post: Post) => (
@skaptelinin можно есть post целиком прокинуть мне, кажется, так лучше, чтобы все поля не описовать.

2023-06-28 08:51 UTC, skaptelinin requested changes

2023-06-28 08:51 UTC, skaptelinin commented on src/components/UI/Loader/Loader.tsx
> +    }}
В таких случаях есть смысл выносить объекты в константу, чтобы при каждом рендере они затово на создавались. У такого подхода есть небольшой минус - нужно доставать тип пропса. Это опциональное замечание.

2023-06-28 08:51 UTC, skaptelinin commented on src/redux/types/posts.ts
> +}
enum для экшенов - очень хорошее решение, молодец)

2023-06-28 08:51 UTC, skaptelinin commented on src/redux/types/posts.ts
> +
В таких случая не нужно плодить кучу типов. В общем, тебе нужно сторого ограничить тип экшена и добавить какую-нибудь типизацию для пейлоада. Для пейлоада можно использовать какой-нибудь юнион (более строгий вариант), либо вариант ниже менее строгий, но его достаточно написать один раз.
```
interface PostAction<Payload extends Partial<PostsState>> {
  type: PostsActionTypesENUM;
  payload?: Payload;
}
```

2023-06-28 09:09 UTC, alexey-samokhin commented on src/components/UI/Loader/Loader.tsx
> +    }}
@skaptelinin можно здесь поподробнее пожалуйста. т.е. при рендере комонента, объект создается заново и тем самым уменьшается производительность? А если мы вынесем обьект в константу, то при ререндере каждый раз будет ссылаться на ячейку памяти.
И что значит в данном примере доставать тип пропса?

2023-07-05 09:10 UTC, skaptelinin requested changes

2023-07-05 09:10 UTC, skaptelinin commented on src/components/UI/Modals/AuthModal/AuthModal.tsx
> +    >
Потенциально у тебя здесь больше двух состояний. В общем случае здесь два варианта решения
1. С помощью роутера - в этом случае ты избавляешься от переменной состояния, она просто переходит в URL
2. switch-case/dictionary. Ты можешь создать словарь с таким интерфейсом
```
type ChildrenDict = Record<AuthModalState, {title: string, component: ReactElement}>
```
И затем просто из него брать все по ключу authModalState

2023-07-05 11:52 UTC, alexey-samokhin commented on src/components/UI/Forms/SignUpForm/SignUpForm.tsx
> +import * as yup from 'yup';
@skaptelinin  лучше не делать из-за большого размера импорта?

2023-07-05 11:58 UTC, alexey-samokhin commented on src/components/UI/Modals/AuthModal/AuthModal.tsx
> +  const isOpen = authModalState === 'signIn' || authModalState === 'signUp';
круто

2023-07-05 12:03 UTC, alexey-samokhin commented on src/components/UI/Modals/AuthModal/AuthModal.tsx
> +  position: 'absolute',
@skaptelinin опять же с офф документации стащил. Если убарть absolute, то модалка будет у верхнего левого угла.

2023-07-05 12:46 UTC, alexey-samokhin commented on src/components/UI/Modals/AuthModal/AuthModal.tsx
> +    >
@skaptelinin пока не могу понять как это реализовать с помощью url. чтобы при открытии модалок url менялся  /signin и /signup соответственно.

2023-07-05 12:53 UTC, skaptelinin commented on src/components/UI/Modals/AuthModal/AuthModal.tsx
> +    >
@alexey-samokhin это просто альтернативный вариант. У тебя это реализовано с помощью состояния, тебе нужно просто заложить поддержку более чем двух состояний.

2023-07-10 09:48 UTC, dsulimenko commented on src/components/Business/Forms/SignUpForm/SignUpForm.tsx
> +        console.log(error.response?.data);
консоль логи лучше убрать перед ПР

2023-07-10 09:51 UTC, dsulimenko approved these changes

2023-07-10 11:23 UTC, skaptelinin requested changes

2023-07-11 08:37 UTC, skaptelinin requested changes

2023-07-11 08:37 UTC, skaptelinin commented on src/redux/auth/saga.ts
> +    takeLatest(AuthActionTypesENUM.REFRESH_SUCCESS, workerUserSaga),
Здесь должен быть REFRESH_REQUEST

2023-07-11 08:37 UTC, skaptelinin commented on src/components/Containers/Header/components/MenuAfterAuth/MenuAfterAuth.tsx
> +        Hello, dear {currentUser && currentUser.username}!
Тоже самое можно записать как
{currentUser?.username}

2023-07-11 08:37 UTC, skaptelinin commented on src/components/Containers/Header/Header.tsx
> +          currentUser?.email
Проще будет сделать проверку на существование currentUser

2023-07-11 08:37 UTC, skaptelinin commented on src/components/Business/Forms/SingInForm/SignInForm.tsx
> +  const handleOnSubmit = async (
По факту это не асинхронная функция

2023-07-11 08:37 UTC, skaptelinin commented on src/components/Business/Forms/SignUpForm/SignUpForm.tsx
> +
Тоже самое - функция на самом деле не асинхронная

2023-07-11 08:37 UTC, skaptelinin commented on src/App.tsx
> +import { refreshSuccess } from './redux/auth/actionCreator';
Здесь должен быть refreshRequest

2023-07-11 09:27 UTC, alexey-samokhin commented on src/components/Containers/Header/Header.tsx
> +          currentUser?.email
что-то туплю вот так же проще или я что-то не то понял.
 {
    currentUser
       ? <MenuAfterAuth className="header__auth" />
            : <MenuBeforeAuth className="header__auth" />
        }

2023-07-11 09:33 UTC, skaptelinin requested changes

2023-07-11 09:33 UTC, skaptelinin commented on src/components/Business/Modals/AuthModal/AuthModal.tsx
> +  const isOpen = {
Здесь достаточно сделать проверку на существование.

2023-07-11 09:33 UTC, skaptelinin commented on src/components/Business/Modals/AuthModal/AuthModal.tsx
> +  const title = {
titlesMap

2023-07-11 09:33 UTC, skaptelinin commented on src/components/Business/Modals/AuthModal/AuthModal.tsx
> +  const form = {
formsMap

2023-07-11 09:33 UTC, skaptelinin commented on src/components/Business/Modals/AuthModal/AuthModal.tsx
> +
Сюда неплохо будет добавить типизацию
```
const titlesMap: Record<AuthModalState,string> = {};

const formsMap: Record<AuthModalState, ReactElement> = {};
```

2023-07-11 09:33 UTC, skaptelinin commented on src/components/Business/Modals/AuthModal/AuthModal.tsx
> +  if (!authModalState) return null;
Выглядит как костыль

2023-07-11 09:33 UTC, skaptelinin commented on src/redux/auth/reducer.ts
> +        currentUser: action?.payload || null,
action гарантированно существует, здесь нет смысла использовать optional chaining

2023-07-11 09:33 UTC, skaptelinin commented on src/redux/auth/saga.ts
> +    yield put(signInSuccess(response.access));
Ты не используешь accessToken в стейте. Проще держать signInSuccess без пейлода

2023-07-11 09:33 UTC, skaptelinin commented on src/redux/auth/saga.ts
> +    yield put(signInSuccess(accessToken));
С твоей структурой стора вызов signInSuccess здесь не нужен.

2023-07-11 09:35 UTC, skaptelinin commented on src/components/Containers/Header/Header.tsx
> +          currentUser?.email
@alexey-samokhin да, пойдет

2023-07-11 11:55 UTC, skaptelinin approved these changes

2023-07-11 12:05 UTC, merged