feat(t11): implementation of adding news
alexey-samokhin/news-site-frontend-samokhin-a pull request #6
Opened 2023-07-17 13:43 UTC by alexey-samokhin

2023-07-18 07:09 UTC, altitovsky requested changes

2023-07-18 07:09 UTC, altitovsky commented on src/interfaces/post.ts
> +  id?: number;
id  не должен быть опциональным

2023-07-18 12:27 UTC, altitovsky requested changes

2023-07-18 12:27 UTC, altitovsky commented on src/components/Pages/ProfilePage/components/UserPostsList/UserPostsList.tsx
> +  useEffect(() => {
у тебя не обновляются посты при создании нового

2023-07-18 13:27 UTC, skaptelinin requested changes

2023-07-18 13:27 UTC, skaptelinin commented on src/components/Pages/MainPage/components/PostsList/PostsList.tsx
> +        <PostItem key={post.id} post={post} />
На будущее - нет ничего плохого в том, чтобы добавлять новые пропсы для компонента. Так ты в коде компонента всегда видишь, что приходит на вход, и требуешь ровно то, что нужно, ни больше ни меньше. В будущем в Post может содержаться куча полей, которые тебе не нужны в рендере, а компонент будет иметь к ним доступ. И это же создаст проблемы при использовании компонента в кейсах, когда у тебя меньше данных, чем того требует интерфейс Post. **Здесь это править не нужно**

2023-07-18 13:27 UTC, skaptelinin commented on src/components/Pages/ProfilePage/ProfilePage.tsx
> +  const handleCloseModal = () => setAuthModalState(null);
По ТЗ можно ли создавать пост на странице чужого юзера? Если нельзя, то здесь также придется делать проверку на автора.

2023-07-18 13:27 UTC, skaptelinin commented on src/components/Pages/ProfilePage/components/UserPostsList/UserPostsList.tsx
> +export const UserPostsList: FC<UserPostsListProps> = ({ userId, username }) => {
Здесь нет смысла делать union. `useState<Post[]>([]);` даст тоже самое.

2023-07-18 13:27 UTC, skaptelinin commented on src/components/Pages/ProfilePage/components/UserPostsList/UserPostsList.tsx
> +        } catch {
Если ты не обрабатываешь ошибку, то проще переписать все в таком виде
```
if (userId) {
        try {
          setIsLoading(true);
          const response = await postsService.getPostsUser(userId);
          setPostsData((state) => [...state, ...response]);
        } finally {
          setIsLoading(false);
        }
      }
```

2023-07-18 13:27 UTC, skaptelinin commented on src/components/Pages/ProfilePage/components/UserPostsList/UserPostsList.tsx
> +          setPostsData((state) => [...state, ...response]);
Здесь нужно переписывать стейт. Иначе у тебя в списке будут оставаться посты предыдущего юзера.

2023-07-18 13:27 UTC, skaptelinin commented on src/components/Pages/ProfilePage/components/UserPostsList/UserPostsList.tsx
> +        {postsData &&
postsData?.map()

2023-07-18 13:27 UTC, skaptelinin commented on src/components/Pages/ProfilePage/components/UserPostsList/UserPostsList.tsx
> +            <Card key={post.id} sx={{ width: '100%', maxWidth: 345 }}>
Лучше вынести это в отдельный компонент

2023-07-18 13:27 UTC, skaptelinin commented on src/interfaces/post.ts
> +  picture?: null;
Если бек может вернуть null, то лучше использовать `string | null`

2023-07-18 13:27 UTC, skaptelinin commented on src/interfaces/tag.ts
> +export interface Tag {
Я бы не стал это выносить в отдельный файл. Тег не существует вне новости.

2023-07-18 13:27 UTC, skaptelinin commented on src/redux/posts/reducer.ts
> +      const newPost = action.payload;
Внутри `switch case` должен быть максимально простой код. Не должно быть условных конструкций, циклов и тд. Если возникает такая необходимость - выноси логику в отдельную функцию.

2023-07-18 13:27 UTC, skaptelinin commented on src/redux/posts/saga.ts
> +export function* workerSetPostSaga(action: PostAction) {
workerCreatePostSaga

2023-07-18 13:27 UTC, skaptelinin commented on src/redux/posts/saga.ts
> +  if (!action.payload) return;
Проще будет контролировать это вне саг. Иначе ты провалишься в validation hell)

2023-07-18 13:27 UTC, skaptelinin commented on src/redux/posts/saga.ts
> +    takeLatest(PostsActionTypesENUM.SET_POST_REQUEST, workerSetPostSaga),
PostsActionTypesENUM.CREATE_POST_REQUEST

2023-07-18 13:43 UTC, alexey-samokhin commented on src/components/Business/Forms/components/Fields/TextField.tsx
> +export const TextField: FC<TextFieldProps> = ({ label, type, name, rows = 1 }) => {
@skaptelinin блин. вот изначально и был отдельный комонент) принял.

2023-07-19 08:00 UTC, skaptelinin requested changes

2023-07-19 09:36 UTC, skaptelinin approved these changes

2023-07-19 11:01 UTC, merged